<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup Condition=" '$(OS)' == 'Windows_NT' ">
    <PackageTargetFrameworks>net461;netstandard2.0;net6</PackageTargetFrameworks>
    <DemoAppTargetFrameworks>net481;net10.0</DemoAppTargetFrameworks>
    <TestTargetFrameworks>net481;net10.0</TestTargetFrameworks>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <AvaloniaVersion>11.0.0</AvaloniaVersion>
    <LatestAvaloniaVersion>11.3.16</LatestAvaloniaVersion>
    <DemoAvaloniaVersion>$(LatestAvaloniaVersion)</DemoAvaloniaVersion>
    <EnableAvaloniaEdit>enabled</EnableAvaloniaEdit>
    <AvaloniaEditVersion>11.0.0</AvaloniaEditVersion>
    <AvaloniaSvgVersion>11.0.0</AvaloniaSvgVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(AVA_VER)' != '' ">
    <TestAvaloniaVersion>$(AVA_VER)</TestAvaloniaVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(AVA_VER)' == '' ">
    <TestAvaloniaVersion>$(LatestAvaloniaVersion)</TestAvaloniaVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageVersion>11.0.3-a1</PackageVersion>
  </PropertyGroup>

</Project>


