<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <PackageTargetFrameworks>net8.0;net10.0</PackageTargetFrameworks>
    <DemoAppTargetFrameworks>net8.0;net10.0</DemoAppTargetFrameworks>
    <TestTargetFrameworks>net8.0;net10.0</TestTargetFrameworks>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <AvaloniaVersion>12.0.0</AvaloniaVersion>
    <DemoAvaloniaVersion>12.1.0</DemoAvaloniaVersion>
    <EnableAvaloniaEdit>enabled</EnableAvaloniaEdit>
    <AvaloniaEditVersion>12.0.0</AvaloniaEditVersion>
    <AvaloniaSvgVersion>12.0.0.1</AvaloniaSvgVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(AVA_VER)' != '' ">
    <TestAvaloniaVersion>$(AVA_VER)</TestAvaloniaVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(AVA_VER)' == '' ">
    <TestAvaloniaVersion>$(DemoAvaloniaVersion)</TestAvaloniaVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageVersion>12.0.0-a3</PackageVersion>
  </PropertyGroup>

</Project>


