<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Markdown.Avalonia.props" />
 
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <LangVersion>$(LangVersion)</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(TestAvaloniaVersion)" />
    <PackageReference Include="Avalonia.Desktop" Version="$(TestAvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="$(TestAvaloniaVersion)" />
  </ItemGroup>
</Project>
