name: .NET on win

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        versions: [ 11.0.0-preview4 ]

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true'
    - name: Install component on windows 2022
      shell: pwsh
      run: |
        Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $componentsToAdd = @(
          "Microsoft.Net.Component.4.6.1.SDK"
        )
        [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        if ($process.ExitCode -eq 0)
        {
            Write-Host "components have been successfully added"
        }
        else
        {
            Write-Host "components were not installed"
            exit 1
        }
    - name: Clean
      run: dotnet clean
      env:
        AVA_VER: ${{ matrix.versions }}
    - name: Restore
      run: dotnet restore
      env:
        AVA_VER: ${{ matrix.versions }}
    - name: Build
      run: dotnet build --no-restore
      env:
        AVA_VER: ${{ matrix.versions }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        AVA_VER: ${{ matrix.versions }}
